// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	CompanyName string `json:"companyName"`
	CompanyID   string `json:"companyID"`
	Location    string `json:"location"`
	Intro       string `json:"intro"`
	Icon        string `json:"icon"`
}

type DashBoard struct {
	User  *User  `json:"user"`
	Title string `json:"title"`
}

type Follow struct {
	UserID      string  `json:"userID"`
	UsersFollow []*User `json:"usersFollow"`
}

type Mutation struct {
}

type Networks struct {
	UserID   string     `json:"userID"`
	Companys []*Company `json:"companys"`
}

type Post struct {
	PostTitle string    `json:"postTitle"`
	PostID    string    `json:"postID"`
	PostUser  *User     `json:"postUser"`
	UserID    string    `json:"userID"`
	Body      string    `json:"body"`
	Comments  []*string `json:"comments"`
	Followers []*User   `json:"followers,omitempty"`
}

type Query struct {
}

type User struct {
	Username       string    `json:"username"`
	Occupation     *Company  `json:"occupation"`
	CompanyFollows *Follow   `json:"companyFollows"`
	Networks       *Networks `json:"networks"`
	Posts          []*Post   `json:"posts"`
}
