package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"iperuranium.com/backend/graph/model"
)

// CreateDashboard is the resolver for the createDashboard field.
func (r *mutationResolver) CreateDashboard(ctx context.Context, title string) (*model.Dashboard, error) {
	panic(fmt.Errorf("not implemented: CreateDashboard - createDashboard"))
}

// UpdateDashboard is the resolver for the updateDashboard field.
func (r *mutationResolver) UpdateDashboard(ctx context.Context, id string, title string) (*model.Dashboard, error) {
	panic(fmt.Errorf("not implemented: UpdateDashboard - updateDashboard"))
}

// DeleteDashboard is the resolver for the deleteDashboard field.
func (r *mutationResolver) DeleteDashboard(ctx context.Context, id string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteDashboard - deleteDashboard"))
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context, id string) (*model.Dashboard, error) {
	return &model.DashBoard{
		Title: "test",
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *dashBoardResolver) User(ctx context.Context, obj *model.DashBoard, id string) (*model.User, error) {
	collection := r.Resolver.MongoDB.Database("GraphQL").Collection("user")
	redisclient := r.Resolver.RedisClient
	var usr model.User

	result, err := redisclient.HGetAll(ctx, id).Result()
	if err != nil || len(result) == 0 {
		log.Println("Redis miss, fetching from MongoDB.")
		err1 := collection.FindOne(ctx, bson.M{"user_id": id}).Decode(&usr)
		if err1 != nil {
			return nil, err1
		}
		redisclient.HSet(ctx, id, map[string]interface{}{
			"username": usr.Username,
		})
	} else {
		usr.Username = result["username"]
		// Fetch other details from Redis if necessary
	}
	return &usr, nil
}
func (r *Resolver) DashBoard() DashBoardResolver { return &dashBoardResolver{r} }
type dashBoardResolver struct{ *Resolver }
*/
